---
name: Wx-Perl-ListCtrl
version: 0.01
author:
  - Mattia Barbon <mbarbon@cpan.org>
abstract: a sensible API for Wx::ListCtrl
license: perl
requires:
  Test::More: 0.50
  Wx: 0.20
provides:
  Wx::Perl::ListCtrl:
    file: lib/Wx/Perl/ListCtrl.pm
    version: 0.01
generated_by: Module::Build version 0.2611
